export const SCREENS = {
  SIGN_UP: 'SIGN UP',
  SIGN_IN: 'SIGN IN',
  SPLASH: 'SPLASH',
  HOME: 'HOME',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PROFILE: 'PROFILE',
  FAVORITES: 'FAVORITES',
  TABS: 'TABS',
  PRODUCT_DETAILS: 'PRODUCT_DETAILS',
  SETTINGS: 'SETTINGS',
  LISTINGS: 'LISTINGS',
  CREATE_LISTINGS: 'CREATE_LISTINGS',
};
